version: '3'

includes:
  common: ./build/Taskfile.yml
  windows: ./build/windows/Taskfile.yml
  darwin: ./build/darwin/Taskfile.yml

vars:
  APP_NAME: "gutgd"
  BIN_DIR: "build/bin"

tasks:
  build:
    cmds:
      - task: "{{OS}}:build"

  run:
    cmds:
      - task: "{{OS}}:run"

  dev:
    cmds:
      - cmd /c "call .\build\windows\cgo-env.cmd wails3 dev -config .\build\config.yml"

  bindings:
    cmds:
      - wails3 generate bindings
