// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * @readonly
 * @enum {string}
 */
export const Availability = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    AvailabilityAvailable: "available",
    AvailabilityUnavailable: "unavailable",
    AvailabilityStubbed: "stubbed",
    AvailabilityUnsupported: "unsupported",
    AvailabilityPermissionBlocked: "permission_blocked",
};

/**
 * @readonly
 * @enum {string}
 */
export const Capability = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    CapabilityMouseMove: "mouse.move",
    CapabilityMouseDrag: "mouse.drag",
    CapabilityMousePosition: "mouse.position",
    CapabilityMouseClick: "mouse.click",
    CapabilityMouseToggle: "mouse.toggle",
    CapabilityMouseScroll: "mouse.scroll",
    CapabilityMouseDelay: "mouse.delay",
    CapabilityKeyboardTap: "keyboard.tap",
    CapabilityKeyboardToggle: "keyboard.toggle",
    CapabilityKeyboardType: "keyboard.type",
    CapabilityKeyboardDelay: "keyboard.delay",
    CapabilityScreenSize: "screen.size",
    CapabilityScreenHighlight: "screen.highlight",
    CapabilityScreenCapture: "screen.capture",
    CapabilityWindowList: "window.list",
    CapabilityWindowActive: "window.active",
    CapabilityWindowRect: "window.rect",
    CapabilityWindowTitle: "window.title",
    CapabilityWindowFocus: "window.focus",
    CapabilityWindowMove: "window.move",
    CapabilityWindowResize: "window.resize",
    CapabilityWindowMinimize: "window.minimize",
    CapabilityWindowRestore: "window.restore",
    CapabilityX11DisplayGet: "x11.display.get",
    CapabilityX11DisplaySet: "x11.display.set",
    CapabilityPermissionReadiness: "permissions.readiness",
    CapabilityAXFocusedWindowMetadata: "ax.window.focused",
    CapabilityAXFocusedElementMetadata: "ax.element.focused",
    CapabilityAXElementAtPointMetadata: "ax.element.at_point",
    CapabilityAXFocusedWindowRaise: "ax.window.raise.focused",
    CapabilityAXFocusedElementAction: "ax.element.action.focused",
    CapabilityAXElementActionAtPoint: "ax.element.action.at_point",
    CapabilityAXElementFocusAtPoint: "ax.element.focus.at_point",
};

export class CapabilityStatus {
    /**
     * Creates a new CapabilityStatus instance.
     * @param {Partial<CapabilityStatus>} [$$source = {}] - The source object to create the CapabilityStatus.
     */
    constructor($$source = {}) {
        if (!("Capability" in $$source)) {
            /**
             * @member
             * @type {Capability}
             */
            this["Capability"] = Capability.$zero;
        }
        if (!("Availability" in $$source)) {
            /**
             * @member
             * @type {Availability}
             */
            this["Availability"] = Availability.$zero;
        }
        if (!("Reason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CapabilityStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CapabilityStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CapabilityStatus(/** @type {Partial<CapabilityStatus>} */($$parsedSource));
    }
}
