// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class BackendInfo {
    /**
     * Creates a new BackendInfo instance.
     * @param {Partial<BackendInfo>} [$$source = {}] - The source object to create the BackendInfo.
     */
    constructor($$source = {}) {
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Platform" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Platform"] = "";
        }
        if (!("BindingState" in $$source)) {
            /**
             * @member
             * @type {BindingState}
             */
            this["BindingState"] = BindingState.$zero;
        }
        if (!("Notes" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["Notes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackendInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BackendInfo}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Notes" in $$parsedSource) {
            $$parsedSource["Notes"] = $$createField3_0($$parsedSource["Notes"]);
        }
        return new BackendInfo(/** @type {Partial<BackendInfo>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const BindingState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    BindingStateLinked: "linked",
    BindingStateUnavailable: "unavailable",
};

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
