// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as Service from "./service.js";
export {
    Service
};

export {
    AXActionAtPointRequest,
    AXActionRequest,
    ActionResult,
    AgentChatMessage,
    AgentChatRequest,
    AgentChatResponse,
    AgentModelOption,
    AgentSettings,
    AgentToolEvent,
    AgentTranscriptItem,
    AgentUsage,
    CaptureRegionRequest,
    CaptureRequest,
    CaptureResult,
    ClipboardCopyRequest,
    ClipboardPasteResult,
    ClipboardState,
    Color,
    ColorPointResult,
    ColorQueryRequest,
    DiagnosticsResponse,
    FeatureStatus,
    FocusedWindowMetadataResult,
    ImagePoint,
    ImagePointTranslationResult,
    KeyboardKeysRequest,
    KeyboardSpecialKeyRequest,
    KeyboardTextRequest,
    MouseButtonRequest,
    MouseDragRequest,
    MouseLineRequest,
    MouseMoveRequest,
    MouseScrollRequest,
    PermissionReadinessResult,
    PermissionSnapshotResult,
    PermissionStatusResult,
    Point,
    PointRequest,
    Region,
    Scale,
    ScreenSizeResult,
    Size,
    UIElementMetadataResult,
    WindowHandleRequest,
    WindowMoveRequest,
    WindowQueryRequest,
    WindowResizeRequest,
    WindowSummary
} from "./models.js";
