// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as guttesting$0 from "../../gut/testing/models.js";

export class ActionResult {
    /**
     * Creates a new ActionResult instance.
     * @param {Partial<ActionResult>} [$$source = {}] - The source object to create the ActionResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActionResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ActionResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ActionResult(/** @type {Partial<ActionResult>} */($$parsedSource));
    }
}

export class CaptureRegionRequest {
    /**
     * Creates a new CaptureRegionRequest instance.
     * @param {Partial<CaptureRegionRequest>} [$$source = {}] - The source object to create the CaptureRegionRequest.
     */
    constructor($$source = {}) {
        if (!("file_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["file_name"] = "";
        }
        if (!("region" in $$source)) {
            /**
             * @member
             * @type {Region}
             */
            this["region"] = (new Region());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CaptureRegionRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CaptureRegionRequest}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("region" in $$parsedSource) {
            $$parsedSource["region"] = $$createField1_0($$parsedSource["region"]);
        }
        return new CaptureRegionRequest(/** @type {Partial<CaptureRegionRequest>} */($$parsedSource));
    }
}

export class CaptureRequest {
    /**
     * Creates a new CaptureRequest instance.
     * @param {Partial<CaptureRequest>} [$$source = {}] - The source object to create the CaptureRequest.
     */
    constructor($$source = {}) {
        if (!("file_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["file_name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CaptureRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CaptureRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CaptureRequest(/** @type {Partial<CaptureRequest>} */($$parsedSource));
    }
}

export class CaptureResult {
    /**
     * Creates a new CaptureResult instance.
     * @param {Partial<CaptureResult>} [$$source = {}] - The source object to create the CaptureResult.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CaptureResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CaptureResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CaptureResult(/** @type {Partial<CaptureResult>} */($$parsedSource));
    }
}

export class ClipboardCopyRequest {
    /**
     * Creates a new ClipboardCopyRequest instance.
     * @param {Partial<ClipboardCopyRequest>} [$$source = {}] - The source object to create the ClipboardCopyRequest.
     */
    constructor($$source = {}) {
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClipboardCopyRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ClipboardCopyRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClipboardCopyRequest(/** @type {Partial<ClipboardCopyRequest>} */($$parsedSource));
    }
}

export class ClipboardPasteResult {
    /**
     * Creates a new ClipboardPasteResult instance.
     * @param {Partial<ClipboardPasteResult>} [$$source = {}] - The source object to create the ClipboardPasteResult.
     */
    constructor($$source = {}) {
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClipboardPasteResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ClipboardPasteResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClipboardPasteResult(/** @type {Partial<ClipboardPasteResult>} */($$parsedSource));
    }
}

export class ClipboardState {
    /**
     * Creates a new ClipboardState instance.
     * @param {Partial<ClipboardState>} [$$source = {}] - The source object to create the ClipboardState.
     */
    constructor($$source = {}) {
        if (!("has_text" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_text"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClipboardState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ClipboardState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClipboardState(/** @type {Partial<ClipboardState>} */($$parsedSource));
    }
}

export class Color {
    /**
     * Creates a new Color instance.
     * @param {Partial<Color>} [$$source = {}] - The source object to create the Color.
     */
    constructor($$source = {}) {
        if (!("r" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["r"] = 0;
        }
        if (!("g" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["g"] = 0;
        }
        if (!("b" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["b"] = 0;
        }
        if (!("a" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["a"] = 0;
        }
        if (!("hex" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hex"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Color instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Color}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Color(/** @type {Partial<Color>} */($$parsedSource));
    }
}

export class ColorPointResult {
    /**
     * Creates a new ColorPointResult instance.
     * @param {Partial<ColorPointResult>} [$$source = {}] - The source object to create the ColorPointResult.
     */
    constructor($$source = {}) {
        if (!("point" in $$source)) {
            /**
             * @member
             * @type {Point}
             */
            this["point"] = (new Point());
        }
        if (!("color" in $$source)) {
            /**
             * @member
             * @type {Color}
             */
            this["color"] = (new Color());
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColorPointResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ColorPointResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("point" in $$parsedSource) {
            $$parsedSource["point"] = $$createField0_0($$parsedSource["point"]);
        }
        if ("color" in $$parsedSource) {
            $$parsedSource["color"] = $$createField1_0($$parsedSource["color"]);
        }
        return new ColorPointResult(/** @type {Partial<ColorPointResult>} */($$parsedSource));
    }
}

export class ColorQueryRequest {
    /**
     * Creates a new ColorQueryRequest instance.
     * @param {Partial<ColorQueryRequest>} [$$source = {}] - The source object to create the ColorQueryRequest.
     */
    constructor($$source = {}) {
        if (!("r" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["r"] = 0;
        }
        if (!("g" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["g"] = 0;
        }
        if (!("b" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["b"] = 0;
        }
        if (!("a" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["a"] = 0;
        }
        if (!("region" in $$source)) {
            /**
             * @member
             * @type {Region | null}
             */
            this["region"] = null;
        }
        if (!("timeout_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timeout_ms"] = 0;
        }
        if (!("interval_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["interval_ms"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColorQueryRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ColorQueryRequest}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("region" in $$parsedSource) {
            $$parsedSource["region"] = $$createField4_0($$parsedSource["region"]);
        }
        return new ColorQueryRequest(/** @type {Partial<ColorQueryRequest>} */($$parsedSource));
    }
}

export class DiagnosticsResponse {
    /**
     * Creates a new DiagnosticsResponse instance.
     * @param {Partial<DiagnosticsResponse>} [$$source = {}] - The source object to create the DiagnosticsResponse.
     */
    constructor($$source = {}) {
        if (!("report" in $$source)) {
            /**
             * @member
             * @type {guttesting$0.EnvironmentReport}
             */
            this["report"] = (new guttesting$0.EnvironmentReport());
        }
        if (!("feature_status" in $$source)) {
            /**
             * @member
             * @type {FeatureStatus[]}
             */
            this["feature_status"] = [];
        }
        if (!("artifacts_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["artifacts_path"] = "";
        }
        if (!("working_dir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["working_dir"] = "";
        }
        if (!("runtime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["runtime"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiagnosticsResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DiagnosticsResponse}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType4;
        const $$createField1_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("report" in $$parsedSource) {
            $$parsedSource["report"] = $$createField0_0($$parsedSource["report"]);
        }
        if ("feature_status" in $$parsedSource) {
            $$parsedSource["feature_status"] = $$createField1_0($$parsedSource["feature_status"]);
        }
        return new DiagnosticsResponse(/** @type {Partial<DiagnosticsResponse>} */($$parsedSource));
    }
}

export class FeatureStatus {
    /**
     * Creates a new FeatureStatus instance.
     * @param {Partial<FeatureStatus>} [$$source = {}] - The source object to create the FeatureStatus.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("availability" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["availability"] = "";
        }
        if (!("reason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FeatureStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FeatureStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FeatureStatus(/** @type {Partial<FeatureStatus>} */($$parsedSource));
    }
}

export class KeyboardKeysRequest {
    /**
     * Creates a new KeyboardKeysRequest instance.
     * @param {Partial<KeyboardKeysRequest>} [$$source = {}] - The source object to create the KeyboardKeysRequest.
     */
    constructor($$source = {}) {
        if (!("keys" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["keys"] = [];
        }
        if (!("auto_delay_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["auto_delay_ms"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KeyboardKeysRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {KeyboardKeysRequest}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("keys" in $$parsedSource) {
            $$parsedSource["keys"] = $$createField0_0($$parsedSource["keys"]);
        }
        return new KeyboardKeysRequest(/** @type {Partial<KeyboardKeysRequest>} */($$parsedSource));
    }
}

export class KeyboardTextRequest {
    /**
     * Creates a new KeyboardTextRequest instance.
     * @param {Partial<KeyboardTextRequest>} [$$source = {}] - The source object to create the KeyboardTextRequest.
     */
    constructor($$source = {}) {
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }
        if (!("auto_delay_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["auto_delay_ms"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KeyboardTextRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {KeyboardTextRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KeyboardTextRequest(/** @type {Partial<KeyboardTextRequest>} */($$parsedSource));
    }
}

export class MouseButtonRequest {
    /**
     * Creates a new MouseButtonRequest instance.
     * @param {Partial<MouseButtonRequest>} [$$source = {}] - The source object to create the MouseButtonRequest.
     */
    constructor($$source = {}) {
        if (!("button" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["button"] = "";
        }
        if (!("auto_delay_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["auto_delay_ms"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MouseButtonRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MouseButtonRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MouseButtonRequest(/** @type {Partial<MouseButtonRequest>} */($$parsedSource));
    }
}

export class MouseDragRequest {
    /**
     * Creates a new MouseDragRequest instance.
     * @param {Partial<MouseDragRequest>} [$$source = {}] - The source object to create the MouseDragRequest.
     */
    constructor($$source = {}) {
        if (!("from_x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["from_x"] = 0;
        }
        if (!("from_y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["from_y"] = 0;
        }
        if (!("to_x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["to_x"] = 0;
        }
        if (!("to_y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["to_y"] = 0;
        }
        if (!("speed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["speed"] = 0;
        }
        if (!("auto_delay_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["auto_delay_ms"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MouseDragRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MouseDragRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MouseDragRequest(/** @type {Partial<MouseDragRequest>} */($$parsedSource));
    }
}

export class MouseLineRequest {
    /**
     * Creates a new MouseLineRequest instance.
     * @param {Partial<MouseLineRequest>} [$$source = {}] - The source object to create the MouseLineRequest.
     */
    constructor($$source = {}) {
        if (!("x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["y"] = 0;
        }
        if (!("speed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["speed"] = 0;
        }
        if (!("auto_delay_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["auto_delay_ms"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MouseLineRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MouseLineRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MouseLineRequest(/** @type {Partial<MouseLineRequest>} */($$parsedSource));
    }
}

export class MouseMoveRequest {
    /**
     * Creates a new MouseMoveRequest instance.
     * @param {Partial<MouseMoveRequest>} [$$source = {}] - The source object to create the MouseMoveRequest.
     */
    constructor($$source = {}) {
        if (!("x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["y"] = 0;
        }
        if (!("auto_delay_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["auto_delay_ms"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MouseMoveRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MouseMoveRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MouseMoveRequest(/** @type {Partial<MouseMoveRequest>} */($$parsedSource));
    }
}

export class MouseScrollRequest {
    /**
     * Creates a new MouseScrollRequest instance.
     * @param {Partial<MouseScrollRequest>} [$$source = {}] - The source object to create the MouseScrollRequest.
     */
    constructor($$source = {}) {
        if (!("direction" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["direction"] = "";
        }
        if (!("amount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["amount"] = 0;
        }
        if (!("auto_delay_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["auto_delay_ms"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MouseScrollRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MouseScrollRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MouseScrollRequest(/** @type {Partial<MouseScrollRequest>} */($$parsedSource));
    }
}

export class Point {
    /**
     * Creates a new Point instance.
     * @param {Partial<Point>} [$$source = {}] - The source object to create the Point.
     */
    constructor($$source = {}) {
        if (!("x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["y"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Point instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Point}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Point(/** @type {Partial<Point>} */($$parsedSource));
    }
}

export class PointRequest {
    /**
     * Creates a new PointRequest instance.
     * @param {Partial<PointRequest>} [$$source = {}] - The source object to create the PointRequest.
     */
    constructor($$source = {}) {
        if (!("x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["y"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PointRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PointRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PointRequest(/** @type {Partial<PointRequest>} */($$parsedSource));
    }
}

export class Region {
    /**
     * Creates a new Region instance.
     * @param {Partial<Region>} [$$source = {}] - The source object to create the Region.
     */
    constructor($$source = {}) {
        if (!("left" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["left"] = 0;
        }
        if (!("top" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["top"] = 0;
        }
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Region instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Region}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Region(/** @type {Partial<Region>} */($$parsedSource));
    }
}

export class ScreenSizeResult {
    /**
     * Creates a new ScreenSizeResult instance.
     * @param {Partial<ScreenSizeResult>} [$$source = {}] - The source object to create the ScreenSizeResult.
     */
    constructor($$source = {}) {
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScreenSizeResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScreenSizeResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScreenSizeResult(/** @type {Partial<ScreenSizeResult>} */($$parsedSource));
    }
}

export class WindowHandleRequest {
    /**
     * Creates a new WindowHandleRequest instance.
     * @param {Partial<WindowHandleRequest>} [$$source = {}] - The source object to create the WindowHandleRequest.
     */
    constructor($$source = {}) {
        if (!("handle" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["handle"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowHandleRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WindowHandleRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowHandleRequest(/** @type {Partial<WindowHandleRequest>} */($$parsedSource));
    }
}

export class WindowMoveRequest {
    /**
     * Creates a new WindowMoveRequest instance.
     * @param {Partial<WindowMoveRequest>} [$$source = {}] - The source object to create the WindowMoveRequest.
     */
    constructor($$source = {}) {
        if (!("handle" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["handle"] = 0;
        }
        if (!("x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["y"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowMoveRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WindowMoveRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowMoveRequest(/** @type {Partial<WindowMoveRequest>} */($$parsedSource));
    }
}

export class WindowQueryRequest {
    /**
     * Creates a new WindowQueryRequest instance.
     * @param {Partial<WindowQueryRequest>} [$$source = {}] - The source object to create the WindowQueryRequest.
     */
    constructor($$source = {}) {
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("use_regex" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["use_regex"] = false;
        }
        if (!("timeout_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timeout_ms"] = 0;
        }
        if (!("interval_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["interval_ms"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowQueryRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WindowQueryRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowQueryRequest(/** @type {Partial<WindowQueryRequest>} */($$parsedSource));
    }
}

export class WindowResizeRequest {
    /**
     * Creates a new WindowResizeRequest instance.
     * @param {Partial<WindowResizeRequest>} [$$source = {}] - The source object to create the WindowResizeRequest.
     */
    constructor($$source = {}) {
        if (!("handle" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["handle"] = 0;
        }
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowResizeRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WindowResizeRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowResizeRequest(/** @type {Partial<WindowResizeRequest>} */($$parsedSource));
    }
}

export class WindowSummary {
    /**
     * Creates a new WindowSummary instance.
     * @param {Partial<WindowSummary>} [$$source = {}] - The source object to create the WindowSummary.
     */
    constructor($$source = {}) {
        if (!("handle" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["handle"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("region" in $$source)) {
            /**
             * @member
             * @type {Region}
             */
            this["region"] = (new Region());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WindowSummary}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("region" in $$parsedSource) {
            $$parsedSource["region"] = $$createField2_0($$parsedSource["region"]);
        }
        return new WindowSummary(/** @type {Partial<WindowSummary>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Region.createFrom;
const $$createType1 = Point.createFrom;
const $$createType2 = Color.createFrom;
const $$createType3 = $Create.Nullable($$createType0);
const $$createType4 = guttesting$0.EnvironmentReport.createFrom;
const $$createType5 = FeatureStatus.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $Create.Array($Create.Any);
