// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as guttesting$0 from "../../gut/testing/models.js";

export class AXActionAtPointRequest {
    /**
     * Creates a new AXActionAtPointRequest instance.
     * @param {Partial<AXActionAtPointRequest>} [$$source = {}] - The source object to create the AXActionAtPointRequest.
     */
    constructor($$source = {}) {
        if (!("x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["y"] = 0;
        }
        if (!("action" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["action"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AXActionAtPointRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AXActionAtPointRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AXActionAtPointRequest(/** @type {Partial<AXActionAtPointRequest>} */($$parsedSource));
    }
}

export class AXActionRequest {
    /**
     * Creates a new AXActionRequest instance.
     * @param {Partial<AXActionRequest>} [$$source = {}] - The source object to create the AXActionRequest.
     */
    constructor($$source = {}) {
        if (!("action" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["action"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AXActionRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AXActionRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AXActionRequest(/** @type {Partial<AXActionRequest>} */($$parsedSource));
    }
}

export class AXElementMatchResult {
    /**
     * Creates a new AXElementMatchResult instance.
     * @param {Partial<AXElementMatchResult>} [$$source = {}] - The source object to create the AXElementMatchResult.
     */
    constructor($$source = {}) {
        if (!("ref" in $$source)) {
            /**
             * @member
             * @type {AXElementRefResult}
             */
            this["ref"] = (new AXElementRefResult());
        }
        if (!("metadata" in $$source)) {
            /**
             * @member
             * @type {UIElementMetadataResult}
             */
            this["metadata"] = (new UIElementMetadataResult());
        }
        if (!("depth" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["depth"] = 0;
        }
        if (!("action_point" in $$source)) {
            /**
             * @member
             * @type {Point}
             */
            this["action_point"] = (new Point());
        }
        if (!("action_point_known" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["action_point_known"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AXElementMatchResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AXElementMatchResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ref" in $$parsedSource) {
            $$parsedSource["ref"] = $$createField0_0($$parsedSource["ref"]);
        }
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField1_0($$parsedSource["metadata"]);
        }
        if ("action_point" in $$parsedSource) {
            $$parsedSource["action_point"] = $$createField3_0($$parsedSource["action_point"]);
        }
        return new AXElementMatchResult(/** @type {Partial<AXElementMatchResult>} */($$parsedSource));
    }
}

export class AXElementRefResult {
    /**
     * Creates a new AXElementRefResult instance.
     * @param {Partial<AXElementRefResult>} [$$source = {}] - The source object to create the AXElementRefResult.
     */
    constructor($$source = {}) {
        if (!("scope" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["scope"] = "";
        }
        if (!("owner_pid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["owner_pid"] = 0;
        }
        if (!("window_handle" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["window_handle"] = 0;
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["path"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AXElementRefResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AXElementRefResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("path" in $$parsedSource) {
            $$parsedSource["path"] = $$createField3_0($$parsedSource["path"]);
        }
        return new AXElementRefResult(/** @type {Partial<AXElementRefResult>} */($$parsedSource));
    }
}

export class ActionResult {
    /**
     * Creates a new ActionResult instance.
     * @param {Partial<ActionResult>} [$$source = {}] - The source object to create the ActionResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActionResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ActionResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ActionResult(/** @type {Partial<ActionResult>} */($$parsedSource));
    }
}

export class AgentChatMessage {
    /**
     * Creates a new AgentChatMessage instance.
     * @param {Partial<AgentChatMessage>} [$$source = {}] - The source object to create the AgentChatMessage.
     */
    constructor($$source = {}) {
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentChatMessage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AgentChatMessage}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AgentChatMessage(/** @type {Partial<AgentChatMessage>} */($$parsedSource));
    }
}

export class AgentChatRequest {
    /**
     * Creates a new AgentChatRequest instance.
     * @param {Partial<AgentChatRequest>} [$$source = {}] - The source object to create the AgentChatRequest.
     */
    constructor($$source = {}) {
        if (!("messages" in $$source)) {
            /**
             * @member
             * @type {AgentChatMessage[]}
             */
            this["messages"] = [];
        }
        if (!("previous_response_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["previous_response_id"] = "";
        }
        if (!("client_run_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["client_run_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentChatRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AgentChatRequest}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField0_0($$parsedSource["messages"]);
        }
        return new AgentChatRequest(/** @type {Partial<AgentChatRequest>} */($$parsedSource));
    }
}

export class AgentChatResponse {
    /**
     * Creates a new AgentChatResponse instance.
     * @param {Partial<AgentChatResponse>} [$$source = {}] - The source object to create the AgentChatResponse.
     */
    constructor($$source = {}) {
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {AgentChatMessage}
             */
            this["message"] = (new AgentChatMessage());
        }
        if (!("tool_events" in $$source)) {
            /**
             * @member
             * @type {AgentToolEvent[]}
             */
            this["tool_events"] = [];
        }
        if (!("items" in $$source)) {
            /**
             * @member
             * @type {AgentTranscriptItem[]}
             */
            this["items"] = [];
        }
        if (!("response_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["response_id"] = "";
        }
        if (!("usage" in $$source)) {
            /**
             * @member
             * @type {AgentUsage}
             */
            this["usage"] = (new AgentUsage());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentChatResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AgentChatResponse}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType4;
        const $$createField1_0 = $$createType7;
        const $$createField2_0 = $$createType9;
        const $$createField4_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("message" in $$parsedSource) {
            $$parsedSource["message"] = $$createField0_0($$parsedSource["message"]);
        }
        if ("tool_events" in $$parsedSource) {
            $$parsedSource["tool_events"] = $$createField1_0($$parsedSource["tool_events"]);
        }
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField2_0($$parsedSource["items"]);
        }
        if ("usage" in $$parsedSource) {
            $$parsedSource["usage"] = $$createField4_0($$parsedSource["usage"]);
        }
        return new AgentChatResponse(/** @type {Partial<AgentChatResponse>} */($$parsedSource));
    }
}

export class AgentModelOption {
    /**
     * Creates a new AgentModelOption instance.
     * @param {Partial<AgentModelOption>} [$$source = {}] - The source object to create the AgentModelOption.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentModelOption instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AgentModelOption}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AgentModelOption(/** @type {Partial<AgentModelOption>} */($$parsedSource));
    }
}

export class AgentSettings {
    /**
     * Creates a new AgentSettings instance.
     * @param {Partial<AgentSettings>} [$$source = {}] - The source object to create the AgentSettings.
     */
    constructor($$source = {}) {
        if (!("api_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["api_key"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("reasoning_effort" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reasoning_effort"] = "";
        }
        if (!("system_prompt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["system_prompt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AgentSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AgentSettings(/** @type {Partial<AgentSettings>} */($$parsedSource));
    }
}

export class AgentToolEvent {
    /**
     * Creates a new AgentToolEvent instance.
     * @param {Partial<AgentToolEvent>} [$$source = {}] - The source object to create the AgentToolEvent.
     */
    constructor($$source = {}) {
        if (!("call_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["call_id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("arguments" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["arguments"] = "";
        }
        if (!("output" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["output"] = "";
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentToolEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AgentToolEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AgentToolEvent(/** @type {Partial<AgentToolEvent>} */($$parsedSource));
    }
}

export class AgentTranscriptItem {
    /**
     * Creates a new AgentTranscriptItem instance.
     * @param {Partial<AgentTranscriptItem>} [$$source = {}] - The source object to create the AgentTranscriptItem.
     */
    constructor($$source = {}) {
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("call_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["call_id"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("arguments" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["arguments"] = "";
        }
        if (!("output" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["output"] = "";
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentTranscriptItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AgentTranscriptItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AgentTranscriptItem(/** @type {Partial<AgentTranscriptItem>} */($$parsedSource));
    }
}

export class AgentUsage {
    /**
     * Creates a new AgentUsage instance.
     * @param {Partial<AgentUsage>} [$$source = {}] - The source object to create the AgentUsage.
     */
    constructor($$source = {}) {
        if (!("input_tokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["input_tokens"] = 0;
        }
        if (!("output_tokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["output_tokens"] = 0;
        }
        if (!("reasoning_tokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["reasoning_tokens"] = 0;
        }
        if (!("total_tokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total_tokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentUsage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AgentUsage}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AgentUsage(/** @type {Partial<AgentUsage>} */($$parsedSource));
    }
}

export class CaptureRegionRequest {
    /**
     * Creates a new CaptureRegionRequest instance.
     * @param {Partial<CaptureRegionRequest>} [$$source = {}] - The source object to create the CaptureRegionRequest.
     */
    constructor($$source = {}) {
        if (!("file_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["file_name"] = "";
        }
        if (!("region" in $$source)) {
            /**
             * @member
             * @type {Region}
             */
            this["region"] = (new Region());
        }
        if (!("max_image_width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["max_image_width"] = 0;
        }
        if (!("max_image_height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["max_image_height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CaptureRegionRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CaptureRegionRequest}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("region" in $$parsedSource) {
            $$parsedSource["region"] = $$createField1_0($$parsedSource["region"]);
        }
        return new CaptureRegionRequest(/** @type {Partial<CaptureRegionRequest>} */($$parsedSource));
    }
}

export class CaptureRequest {
    /**
     * Creates a new CaptureRequest instance.
     * @param {Partial<CaptureRequest>} [$$source = {}] - The source object to create the CaptureRequest.
     */
    constructor($$source = {}) {
        if (!("file_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["file_name"] = "";
        }
        if (!("max_image_width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["max_image_width"] = 0;
        }
        if (!("max_image_height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["max_image_height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CaptureRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CaptureRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CaptureRequest(/** @type {Partial<CaptureRequest>} */($$parsedSource));
    }
}

export class CaptureResult {
    /**
     * Creates a new CaptureResult instance.
     * @param {Partial<CaptureResult>} [$$source = {}] - The source object to create the CaptureResult.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("offset" in $$source)) {
            /**
             * @member
             * @type {Point}
             */
            this["offset"] = (new Point());
        }
        if (!("scale" in $$source)) {
            /**
             * @member
             * @type {Scale}
             */
            this["scale"] = (new Scale());
        }
        if (!("original_size" in $$source)) {
            /**
             * @member
             * @type {Size}
             */
            this["original_size"] = (new Size());
        }
        if (!("delivered_size" in $$source)) {
            /**
             * @member
             * @type {Size}
             */
            this["delivered_size"] = (new Size());
        }
        if (!("original_scale" in $$source)) {
            /**
             * @member
             * @type {Scale}
             */
            this["original_scale"] = (new Scale());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CaptureResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CaptureResult}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType12;
        const $$createField4_0 = $$createType13;
        const $$createField5_0 = $$createType13;
        const $$createField6_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("offset" in $$parsedSource) {
            $$parsedSource["offset"] = $$createField2_0($$parsedSource["offset"]);
        }
        if ("scale" in $$parsedSource) {
            $$parsedSource["scale"] = $$createField3_0($$parsedSource["scale"]);
        }
        if ("original_size" in $$parsedSource) {
            $$parsedSource["original_size"] = $$createField4_0($$parsedSource["original_size"]);
        }
        if ("delivered_size" in $$parsedSource) {
            $$parsedSource["delivered_size"] = $$createField5_0($$parsedSource["delivered_size"]);
        }
        if ("original_scale" in $$parsedSource) {
            $$parsedSource["original_scale"] = $$createField6_0($$parsedSource["original_scale"]);
        }
        return new CaptureResult(/** @type {Partial<CaptureResult>} */($$parsedSource));
    }
}

export class ClipboardCopyRequest {
    /**
     * Creates a new ClipboardCopyRequest instance.
     * @param {Partial<ClipboardCopyRequest>} [$$source = {}] - The source object to create the ClipboardCopyRequest.
     */
    constructor($$source = {}) {
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClipboardCopyRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ClipboardCopyRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClipboardCopyRequest(/** @type {Partial<ClipboardCopyRequest>} */($$parsedSource));
    }
}

export class ClipboardPasteResult {
    /**
     * Creates a new ClipboardPasteResult instance.
     * @param {Partial<ClipboardPasteResult>} [$$source = {}] - The source object to create the ClipboardPasteResult.
     */
    constructor($$source = {}) {
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClipboardPasteResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ClipboardPasteResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClipboardPasteResult(/** @type {Partial<ClipboardPasteResult>} */($$parsedSource));
    }
}

export class ClipboardState {
    /**
     * Creates a new ClipboardState instance.
     * @param {Partial<ClipboardState>} [$$source = {}] - The source object to create the ClipboardState.
     */
    constructor($$source = {}) {
        if (!("has_text" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_text"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClipboardState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ClipboardState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClipboardState(/** @type {Partial<ClipboardState>} */($$parsedSource));
    }
}

export class Color {
    /**
     * Creates a new Color instance.
     * @param {Partial<Color>} [$$source = {}] - The source object to create the Color.
     */
    constructor($$source = {}) {
        if (!("r" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["r"] = 0;
        }
        if (!("g" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["g"] = 0;
        }
        if (!("b" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["b"] = 0;
        }
        if (!("a" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["a"] = 0;
        }
        if (!("hex" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hex"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Color instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Color}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Color(/** @type {Partial<Color>} */($$parsedSource));
    }
}

export class ColorPointResult {
    /**
     * Creates a new ColorPointResult instance.
     * @param {Partial<ColorPointResult>} [$$source = {}] - The source object to create the ColorPointResult.
     */
    constructor($$source = {}) {
        if (!("point" in $$source)) {
            /**
             * @member
             * @type {Point}
             */
            this["point"] = (new Point());
        }
        if (!("color" in $$source)) {
            /**
             * @member
             * @type {Color}
             */
            this["color"] = (new Color());
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColorPointResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ColorPointResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("point" in $$parsedSource) {
            $$parsedSource["point"] = $$createField0_0($$parsedSource["point"]);
        }
        if ("color" in $$parsedSource) {
            $$parsedSource["color"] = $$createField1_0($$parsedSource["color"]);
        }
        return new ColorPointResult(/** @type {Partial<ColorPointResult>} */($$parsedSource));
    }
}

export class ColorQueryRequest {
    /**
     * Creates a new ColorQueryRequest instance.
     * @param {Partial<ColorQueryRequest>} [$$source = {}] - The source object to create the ColorQueryRequest.
     */
    constructor($$source = {}) {
        if (!("r" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["r"] = 0;
        }
        if (!("g" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["g"] = 0;
        }
        if (!("b" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["b"] = 0;
        }
        if (!("a" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["a"] = 0;
        }
        if (!("region" in $$source)) {
            /**
             * @member
             * @type {Region | null}
             */
            this["region"] = null;
        }
        if (!("timeout_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timeout_ms"] = 0;
        }
        if (!("interval_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["interval_ms"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColorQueryRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ColorQueryRequest}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("region" in $$parsedSource) {
            $$parsedSource["region"] = $$createField4_0($$parsedSource["region"]);
        }
        return new ColorQueryRequest(/** @type {Partial<ColorQueryRequest>} */($$parsedSource));
    }
}

export class DiagnosticsResponse {
    /**
     * Creates a new DiagnosticsResponse instance.
     * @param {Partial<DiagnosticsResponse>} [$$source = {}] - The source object to create the DiagnosticsResponse.
     */
    constructor($$source = {}) {
        if (!("report" in $$source)) {
            /**
             * @member
             * @type {guttesting$0.EnvironmentReport}
             */
            this["report"] = (new guttesting$0.EnvironmentReport());
        }
        if (!("feature_status" in $$source)) {
            /**
             * @member
             * @type {FeatureStatus[]}
             */
            this["feature_status"] = [];
        }
        if (!("artifacts_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["artifacts_path"] = "";
        }
        if (!("working_dir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["working_dir"] = "";
        }
        if (!("runtime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["runtime"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiagnosticsResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DiagnosticsResponse}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType16;
        const $$createField1_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("report" in $$parsedSource) {
            $$parsedSource["report"] = $$createField0_0($$parsedSource["report"]);
        }
        if ("feature_status" in $$parsedSource) {
            $$parsedSource["feature_status"] = $$createField1_0($$parsedSource["feature_status"]);
        }
        return new DiagnosticsResponse(/** @type {Partial<DiagnosticsResponse>} */($$parsedSource));
    }
}

export class FeatureStatus {
    /**
     * Creates a new FeatureStatus instance.
     * @param {Partial<FeatureStatus>} [$$source = {}] - The source object to create the FeatureStatus.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("availability" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["availability"] = "";
        }
        if (!("reason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FeatureStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FeatureStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FeatureStatus(/** @type {Partial<FeatureStatus>} */($$parsedSource));
    }
}

export class FocusAXElementRequest {
    /**
     * Creates a new FocusAXElementRequest instance.
     * @param {Partial<FocusAXElementRequest>} [$$source = {}] - The source object to create the FocusAXElementRequest.
     */
    constructor($$source = {}) {
        if (!("ref" in $$source)) {
            /**
             * @member
             * @type {AXElementRefResult}
             */
            this["ref"] = (new AXElementRefResult());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FocusAXElementRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FocusAXElementRequest}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ref" in $$parsedSource) {
            $$parsedSource["ref"] = $$createField0_0($$parsedSource["ref"]);
        }
        return new FocusAXElementRequest(/** @type {Partial<FocusAXElementRequest>} */($$parsedSource));
    }
}

export class FocusAXElementResult {
    /**
     * Creates a new FocusAXElementResult instance.
     * @param {Partial<FocusAXElementResult>} [$$source = {}] - The source object to create the FocusAXElementResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("ref" in $$source)) {
            /**
             * @member
             * @type {AXElementRefResult}
             */
            this["ref"] = (new AXElementRefResult());
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FocusAXElementResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FocusAXElementResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ref" in $$parsedSource) {
            $$parsedSource["ref"] = $$createField1_0($$parsedSource["ref"]);
        }
        return new FocusAXElementResult(/** @type {Partial<FocusAXElementResult>} */($$parsedSource));
    }
}

export class FocusedWindowMetadataResult {
    /**
     * Creates a new FocusedWindowMetadataResult instance.
     * @param {Partial<FocusedWindowMetadataResult>} [$$source = {}] - The source object to create the FocusedWindowMetadataResult.
     */
    constructor($$source = {}) {
        if (!("handle" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["handle"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("subrole" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["subrole"] = "";
        }
        if (!("region" in $$source)) {
            /**
             * @member
             * @type {Region}
             */
            this["region"] = (new Region());
        }
        if (!("region_known" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["region_known"] = false;
        }
        if (!("focused" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["focused"] = false;
        }
        if (!("main" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["main"] = false;
        }
        if (!("minimized" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["minimized"] = false;
        }
        if (!("owner_pid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["owner_pid"] = 0;
        }
        if (!("owner_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["owner_name"] = "";
        }
        if (!("bundle_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["bundle_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FocusedWindowMetadataResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FocusedWindowMetadataResult}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("region" in $$parsedSource) {
            $$parsedSource["region"] = $$createField4_0($$parsedSource["region"]);
        }
        return new FocusedWindowMetadataResult(/** @type {Partial<FocusedWindowMetadataResult>} */($$parsedSource));
    }
}

export class ImagePoint {
    /**
     * Creates a new ImagePoint instance.
     * @param {Partial<ImagePoint>} [$$source = {}] - The source object to create the ImagePoint.
     */
    constructor($$source = {}) {
        if (!("x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["y"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImagePoint instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImagePoint}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImagePoint(/** @type {Partial<ImagePoint>} */($$parsedSource));
    }
}

export class ImagePointTranslationResult {
    /**
     * Creates a new ImagePointTranslationResult instance.
     * @param {Partial<ImagePointTranslationResult>} [$$source = {}] - The source object to create the ImagePointTranslationResult.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("requested_delivered_point" in $$source)) {
            /**
             * @member
             * @type {Point}
             */
            this["requested_delivered_point"] = (new Point());
        }
        if (!("original_image_point" in $$source)) {
            /**
             * @member
             * @type {ImagePoint}
             */
            this["original_image_point"] = (new ImagePoint());
        }
        if (!("exact_screen_point" in $$source)) {
            /**
             * @member
             * @type {ImagePoint}
             */
            this["exact_screen_point"] = (new ImagePoint());
        }
        if (!("absolute_screen_point" in $$source)) {
            /**
             * @member
             * @type {Point}
             */
            this["absolute_screen_point"] = (new Point());
        }
        if (!("capture" in $$source)) {
            /**
             * @member
             * @type {CaptureResult}
             */
            this["capture"] = (new CaptureResult());
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImagePointTranslationResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImagePointTranslationResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType19;
        const $$createField3_0 = $$createType19;
        const $$createField4_0 = $$createType2;
        const $$createField5_0 = $$createType20;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("requested_delivered_point" in $$parsedSource) {
            $$parsedSource["requested_delivered_point"] = $$createField1_0($$parsedSource["requested_delivered_point"]);
        }
        if ("original_image_point" in $$parsedSource) {
            $$parsedSource["original_image_point"] = $$createField2_0($$parsedSource["original_image_point"]);
        }
        if ("exact_screen_point" in $$parsedSource) {
            $$parsedSource["exact_screen_point"] = $$createField3_0($$parsedSource["exact_screen_point"]);
        }
        if ("absolute_screen_point" in $$parsedSource) {
            $$parsedSource["absolute_screen_point"] = $$createField4_0($$parsedSource["absolute_screen_point"]);
        }
        if ("capture" in $$parsedSource) {
            $$parsedSource["capture"] = $$createField5_0($$parsedSource["capture"]);
        }
        return new ImagePointTranslationResult(/** @type {Partial<ImagePointTranslationResult>} */($$parsedSource));
    }
}

export class KeyboardKeysRequest {
    /**
     * Creates a new KeyboardKeysRequest instance.
     * @param {Partial<KeyboardKeysRequest>} [$$source = {}] - The source object to create the KeyboardKeysRequest.
     */
    constructor($$source = {}) {
        if (!("keys" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["keys"] = [];
        }
        if (!("auto_delay_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["auto_delay_ms"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KeyboardKeysRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {KeyboardKeysRequest}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType21;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("keys" in $$parsedSource) {
            $$parsedSource["keys"] = $$createField0_0($$parsedSource["keys"]);
        }
        return new KeyboardKeysRequest(/** @type {Partial<KeyboardKeysRequest>} */($$parsedSource));
    }
}

export class KeyboardSpecialKeyRequest {
    /**
     * Creates a new KeyboardSpecialKeyRequest instance.
     * @param {Partial<KeyboardSpecialKeyRequest>} [$$source = {}] - The source object to create the KeyboardSpecialKeyRequest.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("repeat_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["repeat_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KeyboardSpecialKeyRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {KeyboardSpecialKeyRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KeyboardSpecialKeyRequest(/** @type {Partial<KeyboardSpecialKeyRequest>} */($$parsedSource));
    }
}

export class KeyboardTextRequest {
    /**
     * Creates a new KeyboardTextRequest instance.
     * @param {Partial<KeyboardTextRequest>} [$$source = {}] - The source object to create the KeyboardTextRequest.
     */
    constructor($$source = {}) {
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }
        if (!("auto_delay_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["auto_delay_ms"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KeyboardTextRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {KeyboardTextRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KeyboardTextRequest(/** @type {Partial<KeyboardTextRequest>} */($$parsedSource));
    }
}

export class MouseButtonRequest {
    /**
     * Creates a new MouseButtonRequest instance.
     * @param {Partial<MouseButtonRequest>} [$$source = {}] - The source object to create the MouseButtonRequest.
     */
    constructor($$source = {}) {
        if (!("button" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["button"] = "";
        }
        if (!("auto_delay_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["auto_delay_ms"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MouseButtonRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MouseButtonRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MouseButtonRequest(/** @type {Partial<MouseButtonRequest>} */($$parsedSource));
    }
}

export class MouseDragRequest {
    /**
     * Creates a new MouseDragRequest instance.
     * @param {Partial<MouseDragRequest>} [$$source = {}] - The source object to create the MouseDragRequest.
     */
    constructor($$source = {}) {
        if (!("from_x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["from_x"] = 0;
        }
        if (!("from_y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["from_y"] = 0;
        }
        if (!("to_x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["to_x"] = 0;
        }
        if (!("to_y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["to_y"] = 0;
        }
        if (!("speed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["speed"] = 0;
        }
        if (!("auto_delay_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["auto_delay_ms"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MouseDragRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MouseDragRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MouseDragRequest(/** @type {Partial<MouseDragRequest>} */($$parsedSource));
    }
}

export class MouseLineRequest {
    /**
     * Creates a new MouseLineRequest instance.
     * @param {Partial<MouseLineRequest>} [$$source = {}] - The source object to create the MouseLineRequest.
     */
    constructor($$source = {}) {
        if (!("x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["y"] = 0;
        }
        if (!("speed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["speed"] = 0;
        }
        if (!("auto_delay_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["auto_delay_ms"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MouseLineRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MouseLineRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MouseLineRequest(/** @type {Partial<MouseLineRequest>} */($$parsedSource));
    }
}

export class MouseMoveRequest {
    /**
     * Creates a new MouseMoveRequest instance.
     * @param {Partial<MouseMoveRequest>} [$$source = {}] - The source object to create the MouseMoveRequest.
     */
    constructor($$source = {}) {
        if (!("x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["y"] = 0;
        }
        if (!("auto_delay_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["auto_delay_ms"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MouseMoveRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MouseMoveRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MouseMoveRequest(/** @type {Partial<MouseMoveRequest>} */($$parsedSource));
    }
}

export class MouseScrollRequest {
    /**
     * Creates a new MouseScrollRequest instance.
     * @param {Partial<MouseScrollRequest>} [$$source = {}] - The source object to create the MouseScrollRequest.
     */
    constructor($$source = {}) {
        if (!("direction" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["direction"] = "";
        }
        if (!("amount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["amount"] = 0;
        }
        if (!("auto_delay_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["auto_delay_ms"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MouseScrollRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MouseScrollRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MouseScrollRequest(/** @type {Partial<MouseScrollRequest>} */($$parsedSource));
    }
}

export class PerformAXElementActionOnRefRequest {
    /**
     * Creates a new PerformAXElementActionOnRefRequest instance.
     * @param {Partial<PerformAXElementActionOnRefRequest>} [$$source = {}] - The source object to create the PerformAXElementActionOnRefRequest.
     */
    constructor($$source = {}) {
        if (!("ref" in $$source)) {
            /**
             * @member
             * @type {AXElementRefResult}
             */
            this["ref"] = (new AXElementRefResult());
        }
        if (!("action" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["action"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PerformAXElementActionOnRefRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PerformAXElementActionOnRefRequest}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ref" in $$parsedSource) {
            $$parsedSource["ref"] = $$createField0_0($$parsedSource["ref"]);
        }
        return new PerformAXElementActionOnRefRequest(/** @type {Partial<PerformAXElementActionOnRefRequest>} */($$parsedSource));
    }
}

export class PerformAXElementActionResult {
    /**
     * Creates a new PerformAXElementActionResult instance.
     * @param {Partial<PerformAXElementActionResult>} [$$source = {}] - The source object to create the PerformAXElementActionResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("ref" in $$source)) {
            /**
             * @member
             * @type {AXElementRefResult}
             */
            this["ref"] = (new AXElementRefResult());
        }
        if (!("action" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["action"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PerformAXElementActionResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PerformAXElementActionResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ref" in $$parsedSource) {
            $$parsedSource["ref"] = $$createField1_0($$parsedSource["ref"]);
        }
        return new PerformAXElementActionResult(/** @type {Partial<PerformAXElementActionResult>} */($$parsedSource));
    }
}

export class PermissionReadinessResult {
    /**
     * Creates a new PermissionReadinessResult instance.
     * @param {Partial<PermissionReadinessResult>} [$$source = {}] - The source object to create the PermissionReadinessResult.
     */
    constructor($$source = {}) {
        if (!("permissions" in $$source)) {
            /**
             * @member
             * @type {PermissionSnapshotResult}
             */
            this["permissions"] = (new PermissionSnapshotResult());
        }
        if (!("capabilities" in $$source)) {
            /**
             * @member
             * @type {FeatureStatus[]}
             */
            this["capabilities"] = [];
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PermissionReadinessResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PermissionReadinessResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType22;
        const $$createField1_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("permissions" in $$parsedSource) {
            $$parsedSource["permissions"] = $$createField0_0($$parsedSource["permissions"]);
        }
        if ("capabilities" in $$parsedSource) {
            $$parsedSource["capabilities"] = $$createField1_0($$parsedSource["capabilities"]);
        }
        return new PermissionReadinessResult(/** @type {Partial<PermissionReadinessResult>} */($$parsedSource));
    }
}

export class PermissionSnapshotResult {
    /**
     * Creates a new PermissionSnapshotResult instance.
     * @param {Partial<PermissionSnapshotResult>} [$$source = {}] - The source object to create the PermissionSnapshotResult.
     */
    constructor($$source = {}) {
        if (!("accessibility" in $$source)) {
            /**
             * @member
             * @type {PermissionStatusResult}
             */
            this["accessibility"] = (new PermissionStatusResult());
        }
        if (!("screen_recording" in $$source)) {
            /**
             * @member
             * @type {PermissionStatusResult}
             */
            this["screen_recording"] = (new PermissionStatusResult());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PermissionSnapshotResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PermissionSnapshotResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType23;
        const $$createField1_0 = $$createType23;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("accessibility" in $$parsedSource) {
            $$parsedSource["accessibility"] = $$createField0_0($$parsedSource["accessibility"]);
        }
        if ("screen_recording" in $$parsedSource) {
            $$parsedSource["screen_recording"] = $$createField1_0($$parsedSource["screen_recording"]);
        }
        return new PermissionSnapshotResult(/** @type {Partial<PermissionSnapshotResult>} */($$parsedSource));
    }
}

export class PermissionStatusResult {
    /**
     * Creates a new PermissionStatusResult instance.
     * @param {Partial<PermissionStatusResult>} [$$source = {}] - The source object to create the PermissionStatusResult.
     */
    constructor($$source = {}) {
        if (!("granted" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["granted"] = false;
        }
        if (!("supported" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["supported"] = false;
        }
        if (!("reason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PermissionStatusResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PermissionStatusResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PermissionStatusResult(/** @type {Partial<PermissionStatusResult>} */($$parsedSource));
    }
}

export class Point {
    /**
     * Creates a new Point instance.
     * @param {Partial<Point>} [$$source = {}] - The source object to create the Point.
     */
    constructor($$source = {}) {
        if (!("x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["y"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Point instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Point}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Point(/** @type {Partial<Point>} */($$parsedSource));
    }
}

export class PointRequest {
    /**
     * Creates a new PointRequest instance.
     * @param {Partial<PointRequest>} [$$source = {}] - The source object to create the PointRequest.
     */
    constructor($$source = {}) {
        if (!("x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["y"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PointRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PointRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PointRequest(/** @type {Partial<PointRequest>} */($$parsedSource));
    }
}

export class Region {
    /**
     * Creates a new Region instance.
     * @param {Partial<Region>} [$$source = {}] - The source object to create the Region.
     */
    constructor($$source = {}) {
        if (!("left" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["left"] = 0;
        }
        if (!("top" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["top"] = 0;
        }
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Region instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Region}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Region(/** @type {Partial<Region>} */($$parsedSource));
    }
}

export class Scale {
    /**
     * Creates a new Scale instance.
     * @param {Partial<Scale>} [$$source = {}] - The source object to create the Scale.
     */
    constructor($$source = {}) {
        if (!("x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["y"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Scale instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Scale}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Scale(/** @type {Partial<Scale>} */($$parsedSource));
    }
}

export class ScreenSizeResult {
    /**
     * Creates a new ScreenSizeResult instance.
     * @param {Partial<ScreenSizeResult>} [$$source = {}] - The source object to create the ScreenSizeResult.
     */
    constructor($$source = {}) {
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScreenSizeResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScreenSizeResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScreenSizeResult(/** @type {Partial<ScreenSizeResult>} */($$parsedSource));
    }
}

export class SearchAXElementsRequest {
    /**
     * Creates a new SearchAXElementsRequest instance.
     * @param {Partial<SearchAXElementsRequest>} [$$source = {}] - The source object to create the SearchAXElementsRequest.
     */
    constructor($$source = {}) {
        if (!("scope" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["scope"] = "";
        }
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("subrole" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["subrole"] = "";
        }
        if (!("title_contains" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title_contains"] = "";
        }
        if (!("value_contains" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value_contains"] = "";
        }
        if (!("description_contains" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description_contains"] = "";
        }
        if (!("action" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["action"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean | null}
             */
            this["enabled"] = null;
        }
        if (!("focused" in $$source)) {
            /**
             * @member
             * @type {boolean | null}
             */
            this["focused"] = null;
        }
        if (!("limit" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["limit"] = 0;
        }
        if (!("max_depth" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["max_depth"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchAXElementsRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SearchAXElementsRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchAXElementsRequest(/** @type {Partial<SearchAXElementsRequest>} */($$parsedSource));
    }
}

export class SearchAXElementsResult {
    /**
     * Creates a new SearchAXElementsResult instance.
     * @param {Partial<SearchAXElementsResult>} [$$source = {}] - The source object to create the SearchAXElementsResult.
     */
    constructor($$source = {}) {
        if (!("query" in $$source)) {
            /**
             * @member
             * @type {SearchAXElementsRequest}
             */
            this["query"] = (new SearchAXElementsRequest());
        }
        if (!("matches" in $$source)) {
            /**
             * @member
             * @type {AXElementMatchResult[]}
             */
            this["matches"] = [];
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchAXElementsResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SearchAXElementsResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType24;
        const $$createField1_0 = $$createType26;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("query" in $$parsedSource) {
            $$parsedSource["query"] = $$createField0_0($$parsedSource["query"]);
        }
        if ("matches" in $$parsedSource) {
            $$parsedSource["matches"] = $$createField1_0($$parsedSource["matches"]);
        }
        return new SearchAXElementsResult(/** @type {Partial<SearchAXElementsResult>} */($$parsedSource));
    }
}

export class Size {
    /**
     * Creates a new Size instance.
     * @param {Partial<Size>} [$$source = {}] - The source object to create the Size.
     */
    constructor($$source = {}) {
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Size instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Size}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Size(/** @type {Partial<Size>} */($$parsedSource));
    }
}

export class UIElementMetadataResult {
    /**
     * Creates a new UIElementMetadataResult instance.
     * @param {Partial<UIElementMetadataResult>} [$$source = {}] - The source object to create the UIElementMetadataResult.
     */
    constructor($$source = {}) {
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("subrole" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["subrole"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("focused" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["focused"] = false;
        }
        if (!("frame" in $$source)) {
            /**
             * @member
             * @type {Region}
             */
            this["frame"] = (new Region());
        }
        if (!("frame_known" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["frame_known"] = false;
        }
        if (!("actions" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["actions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UIElementMetadataResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UIElementMetadataResult}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType11;
        const $$createField9_0 = $$createType21;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("frame" in $$parsedSource) {
            $$parsedSource["frame"] = $$createField7_0($$parsedSource["frame"]);
        }
        if ("actions" in $$parsedSource) {
            $$parsedSource["actions"] = $$createField9_0($$parsedSource["actions"]);
        }
        return new UIElementMetadataResult(/** @type {Partial<UIElementMetadataResult>} */($$parsedSource));
    }
}

export class WindowAccessibilityElement {
    /**
     * Creates a new WindowAccessibilityElement instance.
     * @param {Partial<WindowAccessibilityElement>} [$$source = {}] - The source object to create the WindowAccessibilityElement.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("depth" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["depth"] = 0;
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("subrole" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["subrole"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }
        if (!("selected_text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["selected_text"] = "";
        }
        if (!("enabled_known" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled_known"] = false;
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("focused_known" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["focused_known"] = false;
        }
        if (!("focused" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["focused"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Region | null | undefined}
             */
            this["screen_region"] = undefined;
        }
        if (!("available_actions" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["available_actions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowAccessibilityElement instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WindowAccessibilityElement}
     */
    static createFrom($$source = {}) {
        const $$createField13_0 = $$createType15;
        const $$createField14_0 = $$createType21;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("screen_region" in $$parsedSource) {
            $$parsedSource["screen_region"] = $$createField13_0($$parsedSource["screen_region"]);
        }
        if ("available_actions" in $$parsedSource) {
            $$parsedSource["available_actions"] = $$createField14_0($$parsedSource["available_actions"]);
        }
        return new WindowAccessibilityElement(/** @type {Partial<WindowAccessibilityElement>} */($$parsedSource));
    }
}

export class WindowAccessibilityElementActionRequest {
    /**
     * Creates a new WindowAccessibilityElementActionRequest instance.
     * @param {Partial<WindowAccessibilityElementActionRequest>} [$$source = {}] - The source object to create the WindowAccessibilityElementActionRequest.
     */
    constructor($$source = {}) {
        if (!("snapshot_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["snapshot_id"] = "";
        }
        if (!("element_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["element_id"] = "";
        }
        if (!("action" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["action"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowAccessibilityElementActionRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WindowAccessibilityElementActionRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowAccessibilityElementActionRequest(/** @type {Partial<WindowAccessibilityElementActionRequest>} */($$parsedSource));
    }
}

export class WindowAccessibilityElementActionResult {
    /**
     * Creates a new WindowAccessibilityElementActionResult instance.
     * @param {Partial<WindowAccessibilityElementActionResult>} [$$source = {}] - The source object to create the WindowAccessibilityElementActionResult.
     */
    constructor($$source = {}) {
        if (!("snapshot_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["snapshot_id"] = "";
        }
        if (!("element_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["element_id"] = "";
        }
        if (!("action" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["action"] = "";
        }
        if (!("screen_point" in $$source)) {
            /**
             * @member
             * @type {Point}
             */
            this["screen_point"] = (new Point());
        }
        if (!("result" in $$source)) {
            /**
             * @member
             * @type {ActionResult}
             */
            this["result"] = (new ActionResult());
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowAccessibilityElementActionResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WindowAccessibilityElementActionResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType2;
        const $$createField4_0 = $$createType27;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("screen_point" in $$parsedSource) {
            $$parsedSource["screen_point"] = $$createField3_0($$parsedSource["screen_point"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField4_0($$parsedSource["result"]);
        }
        return new WindowAccessibilityElementActionResult(/** @type {Partial<WindowAccessibilityElementActionResult>} */($$parsedSource));
    }
}

export class WindowAccessibilitySnapshotRequest {
    /**
     * Creates a new WindowAccessibilitySnapshotRequest instance.
     * @param {Partial<WindowAccessibilitySnapshotRequest>} [$$source = {}] - The source object to create the WindowAccessibilitySnapshotRequest.
     */
    constructor($$source = {}) {
        if (!("handle" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["handle"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowAccessibilitySnapshotRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WindowAccessibilitySnapshotRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowAccessibilitySnapshotRequest(/** @type {Partial<WindowAccessibilitySnapshotRequest>} */($$parsedSource));
    }
}

export class WindowAccessibilitySnapshotResult {
    /**
     * Creates a new WindowAccessibilitySnapshotResult instance.
     * @param {Partial<WindowAccessibilitySnapshotResult>} [$$source = {}] - The source object to create the WindowAccessibilitySnapshotResult.
     */
    constructor($$source = {}) {
        if (!("snapshot_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["snapshot_id"] = "";
        }
        if (!("window" in $$source)) {
            /**
             * @member
             * @type {WindowSummary}
             */
            this["window"] = (new WindowSummary());
        }
        if (!("element_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["element_count"] = 0;
        }
        if (!("elements" in $$source)) {
            /**
             * @member
             * @type {WindowAccessibilityElement[]}
             */
            this["elements"] = [];
        }
        if (!("markdown" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["markdown"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowAccessibilitySnapshotResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WindowAccessibilitySnapshotResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType28;
        const $$createField3_0 = $$createType30;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("window" in $$parsedSource) {
            $$parsedSource["window"] = $$createField1_0($$parsedSource["window"]);
        }
        if ("elements" in $$parsedSource) {
            $$parsedSource["elements"] = $$createField3_0($$parsedSource["elements"]);
        }
        return new WindowAccessibilitySnapshotResult(/** @type {Partial<WindowAccessibilitySnapshotResult>} */($$parsedSource));
    }
}

export class WindowHandleRequest {
    /**
     * Creates a new WindowHandleRequest instance.
     * @param {Partial<WindowHandleRequest>} [$$source = {}] - The source object to create the WindowHandleRequest.
     */
    constructor($$source = {}) {
        if (!("handle" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["handle"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowHandleRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WindowHandleRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowHandleRequest(/** @type {Partial<WindowHandleRequest>} */($$parsedSource));
    }
}

export class WindowMoveRequest {
    /**
     * Creates a new WindowMoveRequest instance.
     * @param {Partial<WindowMoveRequest>} [$$source = {}] - The source object to create the WindowMoveRequest.
     */
    constructor($$source = {}) {
        if (!("handle" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["handle"] = 0;
        }
        if (!("x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["y"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowMoveRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WindowMoveRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowMoveRequest(/** @type {Partial<WindowMoveRequest>} */($$parsedSource));
    }
}

export class WindowQueryRequest {
    /**
     * Creates a new WindowQueryRequest instance.
     * @param {Partial<WindowQueryRequest>} [$$source = {}] - The source object to create the WindowQueryRequest.
     */
    constructor($$source = {}) {
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("use_regex" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["use_regex"] = false;
        }
        if (!("timeout_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timeout_ms"] = 0;
        }
        if (!("interval_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["interval_ms"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowQueryRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WindowQueryRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowQueryRequest(/** @type {Partial<WindowQueryRequest>} */($$parsedSource));
    }
}

export class WindowResizeRequest {
    /**
     * Creates a new WindowResizeRequest instance.
     * @param {Partial<WindowResizeRequest>} [$$source = {}] - The source object to create the WindowResizeRequest.
     */
    constructor($$source = {}) {
        if (!("handle" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["handle"] = 0;
        }
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowResizeRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WindowResizeRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowResizeRequest(/** @type {Partial<WindowResizeRequest>} */($$parsedSource));
    }
}

export class WindowSummary {
    /**
     * Creates a new WindowSummary instance.
     * @param {Partial<WindowSummary>} [$$source = {}] - The source object to create the WindowSummary.
     */
    constructor($$source = {}) {
        if (!("handle" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["handle"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("region" in $$source)) {
            /**
             * @member
             * @type {Region}
             */
            this["region"] = (new Region());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WindowSummary}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("region" in $$parsedSource) {
            $$parsedSource["region"] = $$createField2_0($$parsedSource["region"]);
        }
        return new WindowSummary(/** @type {Partial<WindowSummary>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = AXElementRefResult.createFrom;
const $$createType1 = UIElementMetadataResult.createFrom;
const $$createType2 = Point.createFrom;
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = AgentChatMessage.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = AgentToolEvent.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = AgentTranscriptItem.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = AgentUsage.createFrom;
const $$createType11 = Region.createFrom;
const $$createType12 = Scale.createFrom;
const $$createType13 = Size.createFrom;
const $$createType14 = Color.createFrom;
const $$createType15 = $Create.Nullable($$createType11);
const $$createType16 = guttesting$0.EnvironmentReport.createFrom;
const $$createType17 = FeatureStatus.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = ImagePoint.createFrom;
const $$createType20 = CaptureResult.createFrom;
const $$createType21 = $Create.Array($Create.Any);
const $$createType22 = PermissionSnapshotResult.createFrom;
const $$createType23 = PermissionStatusResult.createFrom;
const $$createType24 = SearchAXElementsRequest.createFrom;
const $$createType25 = AXElementMatchResult.createFrom;
const $$createType26 = $Create.Array($$createType25);
const $$createType27 = ActionResult.createFrom;
const $$createType28 = WindowSummary.createFrom;
const $$createType29 = WindowAccessibilityElement.createFrom;
const $$createType30 = $Create.Array($$createType29);
