// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {$models.WindowAccessibilityElementActionRequest} req
 * @returns {$CancellablePromise<$models.WindowAccessibilityElementActionResult>}
 */
export function ActOnWindowAccessibilityElement(req) {
    return $Call.ByID(369704685, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.ColorQueryRequest} req
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function AssertColorVisible(req) {
    return $Call.ByID(134871021, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.WindowQueryRequest} req
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function AssertWindowVisible(req) {
    return $Call.ByID(1209703428, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.CaptureRegionRequest} req
 * @returns {$CancellablePromise<$models.CaptureResult>}
 */
export function CaptureRegion(req) {
    return $Call.ByID(3114183722, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {$models.CaptureRequest} req
 * @returns {$CancellablePromise<$models.CaptureResult>}
 */
export function CaptureScreen(req) {
    return $Call.ByID(3981771602, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {$models.AgentChatRequest} req
 * @returns {$CancellablePromise<$models.AgentChatResponse>}
 */
export function ChatWithAgent(req) {
    return $Call.ByID(3875425523, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {$models.MouseButtonRequest} req
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function ClickMouse(req) {
    return $Call.ByID(1763981735, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function ClipboardClear() {
    return $Call.ByID(4221389843).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.ClipboardCopyRequest} req
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function ClipboardCopy(req) {
    return $Call.ByID(1128895767, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.ClipboardState>}
 */
export function ClipboardHasText() {
    return $Call.ByID(3819920489).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.ClipboardPasteResult>}
 */
export function ClipboardPaste() {
    return $Call.ByID(1770450861).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {$models.PointRequest} req
 * @returns {$CancellablePromise<$models.ColorPointResult>}
 */
export function ColorAt(req) {
    return $Call.ByID(4272332838, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {$models.MouseButtonRequest} req
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function DoubleClickMouse(req) {
    return $Call.ByID(2629668814, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.MouseDragRequest} req
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function DragMouse(req) {
    return $Call.ByID(2879309765, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.ColorQueryRequest} req
 * @returns {$CancellablePromise<$models.Point>}
 */
export function FindColor(req) {
    return $Call.ByID(609851502, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {$models.WindowHandleRequest} req
 * @returns {$CancellablePromise<$models.WindowSummary>}
 */
export function FindWindowByHandle(req) {
    return $Call.ByID(3957322820, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @param {$models.WindowQueryRequest} req
 * @returns {$CancellablePromise<$models.WindowSummary>}
 */
export function FindWindowByTitle(req) {
    return $Call.ByID(1623829132, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @param {$models.FocusAXElementRequest} req
 * @returns {$CancellablePromise<$models.FocusAXElementResult>}
 */
export function FocusAXElement(req) {
    return $Call.ByID(1892301927, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @param {$models.PointRequest} req
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function FocusElementAtPoint(req) {
    return $Call.ByID(524922277, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.WindowHandleRequest} req
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function FocusWindow(req) {
    return $Call.ByID(2102876104, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.WindowSummary>}
 */
export function GetActiveWindow() {
    return $Call.ByID(2909843870).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.AgentSettings>}
 */
export function GetAgentSettings() {
    return $Call.ByID(2406893348).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * @param {boolean} mutable
 * @returns {$CancellablePromise<$models.DiagnosticsResponse>}
 */
export function GetDiagnostics(mutable) {
    return $Call.ByID(4177681436, mutable).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * @param {$models.PointRequest} req
 * @returns {$CancellablePromise<$models.UIElementMetadataResult>}
 */
export function GetElementAtPointMetadata(req) {
    return $Call.ByID(100587620, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.UIElementMetadataResult>}
 */
export function GetFocusedElementMetadata() {
    return $Call.ByID(2523385230).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.FocusedWindowMetadataResult>}
 */
export function GetFocusedWindowMetadata() {
    return $Call.ByID(1139212420).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Point>}
 */
export function GetMousePosition() {
    return $Call.ByID(3277626448).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.PermissionReadinessResult>}
 */
export function GetPermissionReadiness() {
    return $Call.ByID(37559861).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.ScreenSizeResult>}
 */
export function GetScreenSize() {
    return $Call.ByID(2197467173).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * @param {$models.WindowAccessibilitySnapshotRequest} req
 * @returns {$CancellablePromise<$models.WindowAccessibilitySnapshotResult>}
 */
export function GetWindowAccessibilitySnapshot(req) {
    return $Call.ByID(46085728, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * @param {$models.Region} req
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function HighlightRegion(req) {
    return $Call.ByID(4261775032, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.AgentModelOption[]>}
 */
export function ListAgentModels() {
    return $Call.ByID(540252835).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.WindowSummary[]>}
 */
export function ListWindows() {
    return $Call.ByID(573994497).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * @param {$models.WindowHandleRequest} req
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function MinimizeWindow(req) {
    return $Call.ByID(764668720, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.MouseButtonRequest} req
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function MouseDown(req) {
    return $Call.ByID(2906832043, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.MouseButtonRequest} req
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function MouseUp(req) {
    return $Call.ByID(26956106, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.MouseLineRequest} req
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function MoveMouseLine(req) {
    return $Call.ByID(1284675706, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.WindowMoveRequest} req
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function MoveWindow(req) {
    return $Call.ByID(335297289, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.PerformAXElementActionOnRefRequest} req
 * @returns {$CancellablePromise<$models.PerformAXElementActionResult>}
 */
export function PerformAXElementAction(req) {
    return $Call.ByID(55535706, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * @param {$models.AXActionAtPointRequest} req
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function PerformElementActionAtPoint(req) {
    return $Call.ByID(885567762, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.AXActionRequest} req
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function PerformFocusedElementAction(req) {
    return $Call.ByID(1823793388, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.KeyboardKeysRequest} req
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function PressKeys(req) {
    return $Call.ByID(2545419963, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.KeyboardSpecialKeyRequest} req
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function PressSpecialKey(req) {
    return $Call.ByID(3576986753, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function RaiseFocusedWindow() {
    return $Call.ByID(71988429).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.KeyboardKeysRequest} req
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function ReleaseKeys(req) {
    return $Call.ByID(2285701249, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.WindowResizeRequest} req
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function ResizeWindow(req) {
    return $Call.ByID(3423318232, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.WindowHandleRequest} req
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function RestoreWindow(req) {
    return $Call.ByID(1589709578, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.AgentSettings} settings
 * @returns {$CancellablePromise<$models.AgentSettings>}
 */
export function SaveAgentSettings(settings) {
    return $Call.ByID(2767597799, settings).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * @param {$models.MouseScrollRequest} req
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function ScrollMouse(req) {
    return $Call.ByID(2159489636, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.SearchAXElementsRequest} req
 * @returns {$CancellablePromise<$models.SearchAXElementsResult>}
 */
export function SearchAXElements(req) {
    return $Call.ByID(3325993616, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType21($result);
    }));
}

/**
 * @param {any} emit
 * @returns {$CancellablePromise<void>}
 */
export function SetEventEmitter(emit) {
    return $Call.ByID(636946090, emit);
}

/**
 * @param {$models.MouseMoveRequest} req
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function SetMousePosition(req) {
    return $Call.ByID(1284603156, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.KeyboardKeysRequest} req
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function TapKeys(req) {
    return $Call.ByID(1028588513, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} path
 * @param {$models.Point} deliveredPoint
 * @returns {$CancellablePromise<$models.ImagePointTranslationResult>}
 */
export function TranslateImagePointToScreen(path, deliveredPoint) {
    return $Call.ByID(3444309878, path, deliveredPoint).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * @param {$models.KeyboardTextRequest} req
 * @returns {$CancellablePromise<$models.ActionResult>}
 */
export function TypeText(req) {
    return $Call.ByID(1856316371, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.ColorQueryRequest} req
 * @returns {$CancellablePromise<$models.Point>}
 */
export function WaitForColor(req) {
    return $Call.ByID(1048117295, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {$models.WindowQueryRequest} req
 * @returns {$CancellablePromise<$models.WindowSummary>}
 */
export function WaitForWindowByTitle(req) {
    return $Call.ByID(1312114077, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.WindowAccessibilityElementActionResult.createFrom;
const $$createType1 = $models.ActionResult.createFrom;
const $$createType2 = $models.CaptureResult.createFrom;
const $$createType3 = $models.AgentChatResponse.createFrom;
const $$createType4 = $models.ClipboardState.createFrom;
const $$createType5 = $models.ClipboardPasteResult.createFrom;
const $$createType6 = $models.ColorPointResult.createFrom;
const $$createType7 = $models.Point.createFrom;
const $$createType8 = $models.WindowSummary.createFrom;
const $$createType9 = $models.FocusAXElementResult.createFrom;
const $$createType10 = $models.AgentSettings.createFrom;
const $$createType11 = $models.DiagnosticsResponse.createFrom;
const $$createType12 = $models.UIElementMetadataResult.createFrom;
const $$createType13 = $models.FocusedWindowMetadataResult.createFrom;
const $$createType14 = $models.PermissionReadinessResult.createFrom;
const $$createType15 = $models.ScreenSizeResult.createFrom;
const $$createType16 = $models.WindowAccessibilitySnapshotResult.createFrom;
const $$createType17 = $models.AgentModelOption.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = $Create.Array($$createType8);
const $$createType20 = $models.PerformAXElementActionResult.createFrom;
const $$createType21 = $models.SearchAXElementsResult.createFrom;
const $$createType22 = $models.ImagePointTranslationResult.createFrom;
