// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as common$0 from "../native/common/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as libnutcore$0 from "../native/libnutcore/models.js";

export class EnvironmentReport {
    /**
     * Creates a new EnvironmentReport instance.
     * @param {Partial<EnvironmentReport>} [$$source = {}] - The source object to create the EnvironmentReport.
     */
    constructor($$source = {}) {
        if (!("ready" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ready"] = false;
        }
        if (!("platform" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["platform"] = "";
        }
        if (!("supported_platform" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["supported_platform"] = false;
        }
        if (!("live_enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["live_enabled"] = false;
        }
        if (!("mutation_enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["mutation_enabled"] = false;
        }
        if (!("mutable_requested" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["mutable_requested"] = false;
        }
        if (!("linux_display_session" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["linux_display_session"] = false;
        }
        if (!("backend" in $$source)) {
            /**
             * @member
             * @type {libnutcore$0.BackendInfo}
             */
            this["backend"] = (new libnutcore$0.BackendInfo());
        }
        if (!("gates" in $$source)) {
            /**
             * @member
             * @type {GateStatus[]}
             */
            this["gates"] = [];
        }
        if (!("reasons" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["reasons"] = [];
        }
        if (!("required_capabilities" in $$source)) {
            /**
             * @member
             * @type {common$0.Capability[]}
             */
            this["required_capabilities"] = [];
        }
        if (!("required_capability_statuses" in $$source)) {
            /**
             * @member
             * @type {common$0.CapabilityStatus[]}
             */
            this["required_capability_statuses"] = [];
        }
        if (!("capabilities" in $$source)) {
            /**
             * @member
             * @type {common$0.CapabilityStatus[]}
             */
            this["capabilities"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnvironmentReport instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EnvironmentReport}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType0;
        const $$createField8_0 = $$createType2;
        const $$createField9_0 = $$createType3;
        const $$createField10_0 = $$createType4;
        const $$createField11_0 = $$createType6;
        const $$createField12_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("backend" in $$parsedSource) {
            $$parsedSource["backend"] = $$createField7_0($$parsedSource["backend"]);
        }
        if ("gates" in $$parsedSource) {
            $$parsedSource["gates"] = $$createField8_0($$parsedSource["gates"]);
        }
        if ("reasons" in $$parsedSource) {
            $$parsedSource["reasons"] = $$createField9_0($$parsedSource["reasons"]);
        }
        if ("required_capabilities" in $$parsedSource) {
            $$parsedSource["required_capabilities"] = $$createField10_0($$parsedSource["required_capabilities"]);
        }
        if ("required_capability_statuses" in $$parsedSource) {
            $$parsedSource["required_capability_statuses"] = $$createField11_0($$parsedSource["required_capability_statuses"]);
        }
        if ("capabilities" in $$parsedSource) {
            $$parsedSource["capabilities"] = $$createField12_0($$parsedSource["capabilities"]);
        }
        return new EnvironmentReport(/** @type {Partial<EnvironmentReport>} */($$parsedSource));
    }
}

export class GateStatus {
    /**
     * Creates a new GateStatus instance.
     * @param {Partial<GateStatus>} [$$source = {}] - The source object to create the GateStatus.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("detail" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["detail"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GateStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GateStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GateStatus(/** @type {Partial<GateStatus>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = libnutcore$0.BackendInfo.createFrom;
const $$createType1 = GateStatus.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = common$0.CapabilityStatus.createFrom;
const $$createType6 = $Create.Array($$createType5);
