import * as Service from '../../bindings/github.com/PandelisZ/gutgd/backend/service.js'
import { callWithRuntime } from './wails'

export const api = {
  getAgentSettings: () => callWithRuntime('GetAgentSettings', () => Service.GetAgentSettings()),
  getAgentSettingsStatus: () => callWithRuntime('GetAgentSettingsStatus', () => Service.GetAgentSettingsStatus()),
  listAgentModels: () => callWithRuntime('ListAgentModels', () => Service.ListAgentModels()),
  saveAgentSettings: (payload) => callWithRuntime('SaveAgentSettings', () => Service.SaveAgentSettings(payload)),
  previewAgentCursor: () => callWithRuntime('PreviewAgentCursor', () => Service.PreviewAgentCursor()),
  chatWithAgent: (payload) => callWithRuntime('ChatWithAgent', () => Service.ChatWithAgent(payload)),
  getDiagnostics: (mutable) => callWithRuntime('GetDiagnostics', () => Service.GetDiagnostics(mutable)),
  typeText: (payload) => callWithRuntime('TypeText', () => Service.TypeText(payload)),
  tapKeys: (payload) => callWithRuntime('TapKeys', () => Service.TapKeys(payload)),
  pressKeys: (payload) => callWithRuntime('PressKeys', () => Service.PressKeys(payload)),
  releaseKeys: (payload) => callWithRuntime('ReleaseKeys', () => Service.ReleaseKeys(payload)),
  getMousePosition: () => callWithRuntime('GetMousePosition', () => Service.GetMousePosition()),
  setMousePosition: (payload) => callWithRuntime('SetMousePosition', () => Service.SetMousePosition(payload)),
  moveMouseLine: (payload) => callWithRuntime('MoveMouseLine', () => Service.MoveMouseLine(payload)),
  clickMouse: (payload) => callWithRuntime('ClickMouse', () => Service.ClickMouse(payload)),
  doubleClickMouse: (payload) => callWithRuntime('DoubleClickMouse', () => Service.DoubleClickMouse(payload)),
  scrollMouse: (payload) => callWithRuntime('ScrollMouse', () => Service.ScrollMouse(payload)),
  dragMouse: (payload) => callWithRuntime('DragMouse', () => Service.DragMouse(payload)),
  getScreenSize: () => callWithRuntime('GetScreenSize', () => Service.GetScreenSize()),
  captureScreen: (payload) => callWithRuntime('CaptureScreen', () => Service.CaptureScreen(payload)),
  captureRegion: (payload) => callWithRuntime('CaptureRegion', () => Service.CaptureRegion(payload)),
  colorAt: (payload) => callWithRuntime('ColorAt', () => Service.ColorAt(payload)),
  highlightRegion: (payload) => callWithRuntime('HighlightRegion', () => Service.HighlightRegion(payload)),
  listWindows: () => callWithRuntime('ListWindows', () => Service.ListWindows()),
  getActiveWindow: () => callWithRuntime('GetActiveWindow', () => Service.GetActiveWindow()),
  getWindowAccessibilitySnapshot: (payload) => callWithRuntime('GetWindowAccessibilitySnapshot', () => Service.GetWindowAccessibilitySnapshot(payload)),
  actOnWindowAccessibilityElement: (payload) => callWithRuntime('ActOnWindowAccessibilityElement', () => Service.ActOnWindowAccessibilityElement(payload)),
  focusWindow: (payload) => callWithRuntime('FocusWindow', () => Service.FocusWindow(payload)),
  minimizeWindow: (payload) => callWithRuntime('MinimizeWindow', () => Service.MinimizeWindow(payload)),
  restoreWindow: (payload) => callWithRuntime('RestoreWindow', () => Service.RestoreWindow(payload)),
  moveWindow: (payload) => callWithRuntime('MoveWindow', () => Service.MoveWindow(payload)),
  resizeWindow: (payload) => callWithRuntime('ResizeWindow', () => Service.ResizeWindow(payload)),
  findColor: (payload) => callWithRuntime('FindColor', () => Service.FindColor(payload)),
  waitForColor: (payload) => callWithRuntime('WaitForColor', () => Service.WaitForColor(payload)),
  assertColorVisible: (payload) => callWithRuntime('AssertColorVisible', () => Service.AssertColorVisible(payload)),
  findWindowByTitle: (payload) => callWithRuntime('FindWindowByTitle', () => Service.FindWindowByTitle(payload)),
  waitForWindowByTitle: (payload) => callWithRuntime('WaitForWindowByTitle', () => Service.WaitForWindowByTitle(payload)),
  assertWindowVisible: (payload) => callWithRuntime('AssertWindowVisible', () => Service.AssertWindowVisible(payload)),
  clipboardCopy: (payload) => callWithRuntime('ClipboardCopy', () => Service.ClipboardCopy(payload)),
  clipboardPaste: () => callWithRuntime('ClipboardPaste', () => Service.ClipboardPaste()),
  clipboardClear: () => callWithRuntime('ClipboardClear', () => Service.ClipboardClear()),
  clipboardHasText: () => callWithRuntime('ClipboardHasText', () => Service.ClipboardHasText())
}
